# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host:     localhost
  database: highlearn
  username: highlearn
  password: highlearn_123456

test:
  <<: *default
  host:     localhost
  database: highlearn_test
  username: highlearn
  password: highlearn_123456

production:
  <<: *default
  host:     localhost
  database: highlearn
  username: highlearn
  password: highlearn_123456
